CREATE TABLE `test.unconfirmed_transactions` (
	`index` BIGINT, 
	lock_time FLOAT(53), 
	ver FLOAT(53), 
	size FLOAT(53), 
	weight FLOAT(53), 
	`time` FLOAT(53), 
	tx_index FLOAT(53), 
	vin_sz FLOAT(53), 
	hash TEXT, 
	vout_sz FLOAT(53), 
	relayed_by TEXT, 
	rbf BOOL, 
	sequence BIGINT, 
	witness TEXT, 
	script TEXT, 
	`prev_out.spent` BOOL, 
	`prev_out.spending_outpoints` TEXT, 
	`prev_out.tx_index` BIGINT, 
	`prev_out.type` BIGINT, 
	`prev_out.addr` TEXT, 
	`prev_out.value` BIGINT, 
	`prev_out.n` BIGINT, 
	`prev_out.script` TEXT, 
	spent BOOL, 
	type FLOAT(53), 
	addr TEXT, 
	value FLOAT(53), 
	n FLOAT(53), 
	spending_outpoints TEXT, 
	CHECK (rbf IN (0, 1)), 
	CHECK (`prev_out.spent` IN (0, 1)), 
	CHECK (spent IN (0, 1))
)